title: "Shibani Roychoudhury"
title_alignment: "center"
logo: /assets/img/MyprofileImage.png
description: |
  <p align="center">
    <a href="pdf/resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/shibaniroychoudhury/">LinkedIn</a> |
    <a href="https://github.com/helloshibani">GitHub</a>
    <br>
    I'm currently pursuing a PG-Diploma in Data Science and AI and have over 13 years of experience in software development and client management. My journey has been a blend of technology and business, giving me a unique perspective on delivering impactful solutions.
    <br>
  </p>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
