title: "Shibani Roychoudhury"
title_alignment: "center"
logo: /assets/img/MyprofileImage.png
description: |
  <p align="center">
    <a href="pdf/resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/shibaniroychoudhury/">LinkedIn</a> |
    <a href="https://github.com/helloshibani">GitHub</a>
    <br>
    👋 Hi, I'm Shibani Roychoudhury
    I'm a passionate Data Science professional with 15+ years of experience in software development, payroll processing systems, and client management. Currently pursuing a Post Graduate Diploma in Data Science and AI.
    
    I love solving complex problems, analyzing data, and applying ML techniques to real-world challenges. Always keen to learn and grow in the tech space!
    <br>
  </p>
  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
